### ISSUE TITLE
New weight classes are not instantly shown the league overview

### ISSUE THREAD

**Issue by Zomtir** [Oberhauser-Dev/wrestling_scoreboard#11]
Adding a new weight class does not refresh the parent league overview.

**Comment by Gustl22** [comment]
Can you reevaluate if this issue still persists after the changes?
https://wrestling-scoreboard.oberhauser.dev/
I didn't experience that any more.

But I noticed if editing a weight class, the weight class info is not updated.

**Comment by Zomtir** [comment]
I can reproduce neither, both seem fixed. A new weight class does show up in the parent league. Changing any details of the class will update immediately  in the parent league.
