### ISSUE TITLE
League should not be a single property of a team

### ISSUE THREAD

**Issue by Zomtir** [Oberhauser-Dev/wrestling_scoreboard#7]
A team must be able to be part of multiple leagues rather a single one (n:n relationship).

There might be multiple leagues happening at once and a new season should not invalidate present data.

E.g. FC Bayern I (first team) might be part of Champions League 2022, Champions League 2023,  1. Bundesliga 2023 and 2. Bundesliga 2024.

Consequences:
- The assignment of a league in the team edit panel is not really needed. If the functionality shall remain, the assignment needs to be dedicated modifiable list rather than a drop-down.

**Comment by Gustl22** [comment]
Fixed in 853a5c0
